[package]
name = "caniemail"
version = "0.1.0-alpha.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[dependencies]
html_parser.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
