[package]
name = "email-components-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
tidier = "0.5.3"
tokio = { version = "1.47.0", features = ["full"] }
yew = { version = "0.21.0", features = ["ssr"] }
